yondonfu/comfystream

setup.py
Until this comfyui PR is merged https://github.com/hiddenswitch/ComfyUI/pull/26
=> Pin opentelemetry versions

server/app.py
This change fixes a typo found in server/app.py
=> fix typo in logger

ui/src/components/room.tsx, ui/src/components/settings.tsx, ui/src/components/webcam.tsx
This pull request improves the layout and responsiveness of the preview video on mobile devices,
ensuring a better user experience by addressing compatibility and display issues.
=> feat(ui): enhance preview video layout for mobile devices

README.md, ui/.gitignore, ui/package.json, ui/src/app/globals.css, ui/src/components/room.tsx, ui/src/components/settings.tsx, ui/src/components/ui/input.tsx, ui/src/components/ui/select.tsx
This pull request enhances mobile responsiveness in ComfyStream by centering the streamer view on mobile and tablet devices. Prevents iOS from auto-zooming inputs by applying iOS-specific CSS classes. Additionally, introduces a new launch command for starting the dev server with an SSH certificate.
=> refactor(ui): enhance mobile compatibility for stream view

configs/nodes.yaml
Updates nodes.yaml in configs to add Yondon's ComfyUI-Background-Edit nodes to support the background changing workflows.
=> Add ComfyUI-Background-Edit to default nodes

.devcontainer/README.md, workflows/ui/3 - SD 1.5 TensorRT workflow.json
This change updates the sample workflow, which was missing the TensorRT node
=> update SD 1.5 workflow

ui/.github/ISSUE_TEMPLATE/bug_report.yml, ui/.github/ISSUE_TEMPLATE/feature_request.yml
This pull request adds issue templates to guide users in submitting bug reports and feature requests. The templates help ensure that the submitted issues contain the necessary information, making it easier for developers to understand and
address them.
=> chore: Add issue templates for bug reports and feature requests

docker/entrypoint.sh
Resolves an issue when build depth-anything engine. Creates missing directory `/workspace/ComfyUI/models/tensorrt/depth-anything`
=> fix: create tensorrt/depth-anything dir

.devcontainer/post-create.sh
This pull request ensures that the comfystream package is installed in editable mode so that code changes are directly reflected in the dev environment.
=> chore: install dev container comfystream in edit mode

ui/src/components/room.tsx, ui/src/components/settings.tsx
Ensures devices are listed and permissions are checked correctly. Also updates variable and method names to be consistent with audio or video devices
=> fix(ui): audio video devices selection

ui/src/components/room.tsx
This pull request ensures that the output video stream element takes the full height of its parent div, improving layout consistency and visual alignment.
=> fix(ui): ensure proper alignment of output stream video

configs/nodes.yaml, server/app.py, setup.py, workflows/regional_lora.json
This bumps the hiddenswitch dependency, allowing for the use of node packs that take advantage of newer features in ComfyUI, as well as the core Hook system enhancement which will enable the use of LoRAs with the SD1.5 TensorRT workflow.
Fixes #2 
Supersedes #19
Without the addition of this explicit CUDA initialization, we get warnings like:
```
torch.cuda.current_device() did not return a device, returning a CPU torch device
```
The use of CPU torch device predictably results in a core dump.
###Testing
After updating setup.py with newer commit hash, reinstalled ComfyStream with
```
pip uninstall comfystream
cd path/to/ComfyStream
pip install -e .
```
Then, tested with all workflows from here:
https://github.com/yondonfu/comfystream/blob/main/workflows/tensor-utils-example-workflow.json …
=> feat: upgrade hiddenswitch

ui/src/components/settings.tsx
This change removes erroneous lines added in #44
=> chore(ui): remove unused ui select option code

workflows/ui/SD 1.5 MultiControlNet DepthAnything Face.json, workflows/ui/SD 1.5 TensorRT w DepthMask accelerated.json
Adds the sample workflow to ComfyUI examples for the DepthAnything Background Fix DepthMask workflow
=> chore(dev): add sample workflow for background fix

setup.py
Update ComfyStream package ver to align with new version convention
=> bump: comfystream version to 0.0.2

workflows/ui/SD 1.5 TensorRT w DepthMask accelerated.json
This change updates the background workflow to use the correct engine and filenames
=> fix(dev): update the depthmask background workflow

ui/src/app/page.tsx, ui/src/components/control-panel.tsx, ui/src/components/peer.tsx, ui/src/components/room.tsx, ui/src/components/settings.tsx, ui/src/components/webcam.tsx, ui/src/hooks/use-peer.ts, ui/src/types/index.ts, ui/src/types/types.ts
This pull request fixes several eslint errors in the codebase so that the UI can be succesfully build and distributed.
=> chore(ui): fix eslint errors so UI builds

README.md, scripts/README.md, scripts/config/cloud_init_comfystream.yaml, scripts/config/cloud_init_comfystream_template.yaml, scripts/requirements.txt, scripts/spinup_comfystream_tensordock.py
This pull request adds a script that users can use the spinup a VM running Comfystream on tensordock.
=> feat: add comfystream tensordock spinup script

scripts/README.md, scripts/config/cloud_init_comfystream_template.yaml, scripts/requirements.txt, scripts/spinup_comfystream_tensordock.py
This pull request implements HTTPS support for the ComfUI interface and refactored parts of the codebase for better maintainability.
=> feat(dev): enable https for ComfyUI interface

.github/workflows/release.yaml, pyproject.toml, ui/package.json
Updates package version to 0.0.3
=> release: update version to 0.0.3

.github/workflows/comfyui-base.yaml, .github/workflows/docker.yaml, .github/workflows/release.yaml
Rename ui-kit release workflow
=> workflows: Disable github action unless running in livepeer fork

server/app.py, server/utils.py
This pull request extracts the FPS statistics collection into its own class to keep the `VideoStreamTrack` implementation cleaner and more maintainable. This also makes the logic reusable across different components.
=> refactor(server): improve FPS Stats collection logic

ui/src/components/settings.tsx
This pull request gives users the ability to set the stream settings using query parameters.
=> feat(ui): add settings search queries

prestartup_script.py
Fixes a file not found error caused by https://github.com/yondonfu/comfystream/pull/136 which didn't fully remove the startup script
=> fix: remove missing startup script

ui/package-lock.json, ui/package.json
Reverts yondonfu/comfystream#142
=> Revert "chore(deps-dev): bump tailwindcss from 3.4.17 to 4.0.12 in /ui"

ui/package-lock.json, ui/package.json
Reverts yondonfu/comfystream#105
=> Revert "chore(deps): bump tailwind-merge from 2.6.0 to 3.0.2 in /ui"

.devcontainer/README.md
Fixes an invalid file path in the devcontainer docs
=> dev: update devcontainer documentation

.gitignore, server/app.py
This fix starts ComfyUI with the latent preview feature disabled.
This is for two reasons:
1. This has an unknown nonzero performance impact. This is a feature of ComfyUI where individual denoising steps are decoded from the latent space and shown as a preview. Regardless, we do not use latent preview, so we should disable it.
2. I occasionally have been getting the following error, which clued me in to the fact that the latent preview feature is enabled. It may be enabled by default when taesd vae is present. Disabling the use of latent_preview.py would prevent this error:
`Error running prompt: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider …
=> fix: disable latent preview

workflows/comfystream/sd15-multi-cnet-depthanything-face-api.json, workflows/comfystream/sd15-multi-cnet-depthanything-o2o-api.json, workflows/comfyui/sd15-multi-cnet-depthanything-face.json, workflows/comfyui/sd15-multi-cnet-depthanything-o2o.json
adds new feature bank node to improve temporal consistency
=> feat: add feature bank node

pyproject.toml, ui/package-lock.json, ui/package.json
Updates the package version to 0.0.4 for next release
=> chore: update package ver to 0.0.4
