yondonfu/comfystream

ui/package-lock.json, ui/package.json, ui/src/components/room.tsx, ui/src/components/settings.tsx, ui/src/components/ui/select.tsx, ui/src/components/webcam.tsx, ui/src/hooks/use-peer.ts
This is a copy of https://github.com/yondonfu/comfystream/pull/3 with resolved merge conflicts.
=> (COPY) ui: Add camera selector to input

ui/package-lock.json, ui/package.json, ui/src/components/room.tsx, ui/src/components/ui/tooltip.tsx, ui/src/components/webcam.tsx
Fixes https://github.com/yondonfu/comfystream/issues/9
The FPS reported for the input stream player is actually the requested FPS because that was easier to implement for now. Technically, there are different FPS values that could be reported here - the actual FPS of the video if it is different from what was requested, the FPS of the outbound WebRTC stream. The current code structure makes these other values a little trickier to implement so I figured let's just get *some* indicator in for now so the user remembers what FPS they requested initially. In order to provide some more clarity, both the input and output FPS indicators have hover tooltips that describe the exact nature of the reported value.
This is what the input FPS indicator looks like:
This is what the output FPS indicator …
=> ui: Add input/output FPS indicators

ui/src/components/settings.tsx
This pull request changes the default stream url to the local development server so that users can just click start if they have the Comfystream server running. @yondonfu is there a reason we set the UI url as the default stream url?
=> refactor(ui): change default stream url

server/app.py
This change sets the logging level for `aiortc.rtcrtpsender` and `aiortc.rtcrtpreceiver` to warning so that there are not so many logs to look through. These classes were not logging at the same level as the application
=> Set log level to warning for verbose aiortc logs

ui/src/components/settings.tsx, ui/src/components/ui/input.tsx
This commit updates the Comfy Workflow input to be a required field. This change ensures that users must provide a workflow file before starting the stream, which helps mitigate issues due to the current lack of robust error handling.
@eliteprox, @yondonfu another way would to use [load-preview-image-example-workflow](https://github.com/yondonfu/comfystream/blob/main/workflows/load-preview-image-example-workflow.json) when no workflow is required but I think this might cause more confusion.
=> refactor: make Comfy Workflow input required

workflows/ui/3 - SD 1.5 TensorRT workflow.json
Changes the name of the tensorrt engine used in the example workflow back to the same as that produced by running the Build ONNX/Build Static TensorRT examples or scripts/build_trt.py
=> revert tensorrt engine name change in workflow 3

ui/src/components/control-panel.tsx, ui/src/components/control-panels-container.tsx
- Maintain values across drawer open/close cycles
- Move panel state to container component
- Pass state down as props to control panels
=> feat: persist control panel state when drawer closes

ui/src/components/settings.tsx, ui/src/components/ui/select.tsx
This pull request enhances the camera selection functionality to prevent user confusion due
to lack of solid error handling. It includes the following improvements:
- Ensures the camera field is required, displaying a warning if no camera is selected.
- Fixes the camera state setting to correctly select the first device, preventing it
from being overwritten with an empty string.
- Displays a descriptive label when no camera devices are available.
Additionally, this commit improves the codebase structure for better maintainability
and readability.
=> feat: improve camera selection behavior

configs/nodes.yaml
Removes kj-nodes and comfyui-manager from nodes.yaml since they are not used in a default workflow
=> Remove kj-nodes and comfyui-manager

.devcontainer/README.md
This pull request ensure that the right folder path is used in the model download command.
=> docs(dev): fixes an incorrect model download command

.devcontainer/README.md, .devcontainer/post-create.sh
This pull request adds a new `prepare_examples` alias to the dev container that users can use to setup all the dependencies for the examples. It also updates the documentation.
=> refactor: improve the example setup

docker/Dockerfile.base, nodes/audio_utils/__init__.py, nodes/audio_utils/load_audio_tensor.py, nodes/audio_utils/pitch_shift.py, nodes/audio_utils/save_audio_tensor.py, nodes/tensor_utils/load_tensor.py, server/app.py, server/pipeline.py, src/comfystream/client.py, src/comfystream/tensor_cache.py, src/comfystream/utils.py, ui/src/app/api/offer/route.ts, ui/src/app/page.tsx, ui/src/components/control-panel.tsx, ui/src/components/peer.tsx, ui/src/components/room.tsx, ui/src/components/settings.tsx, ui/src/components/webcam.tsx, ui/src/hooks/use-peer.ts, workflows/audio-tensor-utils-example-workflow.json
This PR aims to add audio support to comfystream. It adds the following functionalities
1. Instead of invoking queue_prompt after each frame push, it's now run in a loop and queue connects stream track and comfyui workflow, audio and video get to server at different rates to invoking queue_prompt after pushing each frame isn't feasible
2. Can select 3 kinds of permutations with two tracks video and audio (video only, audio only, video + audio)
3. Ability to run multiple prompts concurrently -- the reason for this is we don't want one workflow(prompt) to affect another prompt (this occurs mostly due to buffering which is mostly needed in audio workflows), also if two workflows are not dependent, they should be run on separate threads for concurrency 
Future Work:
1. Explore one-to-many …
=> feat: audio support 

.devcontainer/post-create.sh
Reverts yondonfu/comfystream#65 because it installs in the base environment
=> Revert "chore: install dev container comfystream in edit mode"

.devcontainer/Dockerfile, .devcontainer/entrypoint.sh, .devcontainer/post-create.sh
This pull request ensures that the behavior of the dev container is more consistent with what developers would expect when using the dev container Docker image as a standalone image.
=> chore(dev): remove nested bash shell

install.py
This allows for vanilla ComfyUI and the Hiddenswitch fork to be installed and used in the same python environment. This is based directly on the advice of the author of the Hiddenswitch fork.
Without this fix, we get messages like the following when starting ComfyUI in the same python environment as Hiddenswitch:
`AttributeError: module 'comfy.utils' has no attribute 'set_progress_bar_global_hook'. Did you mean: 'set_progress_bar_enabled'?
`
and 
`ModuleNotFoundError: No module named 'comfy_extras.nodes_slg'`
These errors occur because Python's module system requires proper `__init__.py` files to recognize directories as packages, and the current setup doesn't ensure these files exist in all necessary directories. Thus far, the solution has been maintaining two separate python …
=> improvement: single python environment

pyproject.toml, setup.py
This change updates the comfystream package installation to the latest standard. See https://packaging.python.org/en/latest/guides/modernize-setup-py-project/ and additional warning https://github.com/pypa/pip/issues/11457
Resolves https://github.com/yondonfu/comfystream/issues/35
=> add pyproject.toml to remove deprecation warning

configs/nodes.yaml
Now that https://github.com/yondonfu/ComfyUI_TensorRT/pull/1 has been merged we should revert to using the correct branch for ComfyUI_TensorRT node
=> chore: update tensorrt node

docker/Dockerfile.base
This change ensures that only comfyui compatible workflows are copied into the user workspace
=> remove api workflows from comfyui workspace

nodes/api/__init__.py, nodes/web/js/comfystream_ui_preview_node.js, nodes/web/js/launcher.js
When running on RunPod, clicking the "Open ComfyStream UI" button failed to open the UI in a new tab. This was caused by:
1. The backend using `webbrowser.open()` which only works locally
2. Not accounting for RunPod's proxy URL structure (e.g., `https://zsxfe3108tiubt-8188.proxy.runpod.net/`)
- Removed server-side browser opening logic
- Updated client-side code to use `window.location.origin` to get the current base URL
- Standardized all UI opening code to use the `/comfystream/extension_info` endpoint
- Removed the now-redundant `/launch_comfystream` endpoint
- Updated both the menu launcher and UI preview node to use the same approach
This fix ensures the UI opens correctly in both local and RunPod environments without environment-specific code.
supersedes #108
=> fix: open UI in new tab

pyproject.toml
Adds a publisher id for publishing the node to the registry
=> chore: add publisher-id for registry publication

install.py
This change ensures that the latest UI files are downloaded even when the current version UI files are not published yet
=> download latest ui files when missing

src/comfystream/scripts/setup_models.py
This issue resolves an error with ComfyUI missing the models/LLM folder due to volume mount override.
We can alternatively add the Florence2 model to `models.yaml` if preferred
```
[ERROR] An error occurred while retrieving information for the 'Florence2ModelLoader' node.
Traceback (most recent call last):
File "/workspace/ComfyUI/server.py", line 591, in get_object_info
out[x] = node_info(x)
^^^^^^^^^^^^
File "/workspace/ComfyUI/server.py", line 558, in node_info
info['input'] = obj_class.INPUT_TYPES()
^^^^^^^^^^^^^^^^^^^^^^^
File "/workspace/ComfyUI/custom_nodes/ComfyUI-Florence2-Vision/nodes.py", line 169, in INPUT_TYPES
"model": ([item.name for item in Path(folder_paths.models_dir, "LLM").iterdir() if item.is_dir()], {"tooltip": "models are expected to be in Comfyui/models folder"}), …
```
=> fix: add missing LLM folder

configs/nodes.yaml, docker/Dockerfile.base
This change unpins `mediapipe==0.10.8` which was previously done to enable ComfyUI MediaPipe ControlNets https://github.com/yondonfu/comfystream/pull/78#issuecomment-2675094698
=> fix: mediapipe conflict with protbuf in ComfyUI_TensorRT

nodes/tensor_utils/prestartup_script.py
This pull request ensures that the patched torch graph remains synchronized even when an error occurs during inference, preventing potential inconsistencies.
=> fix: ensure patched torch graph is always synced on inference errors

ui/src/components/settings.tsx
Resolves issue with default camera device being selected https://github.com/yondonfu/comfystream/issues/119 by checking for empty values being passed to `handleCameraSelect` from the UI.
Also reverts most of https://github.com/yondonfu/comfystream/pull/82 which wasn't working correctly either. This will unblock the UI for easier development of simultaneous workflows while keeping the audio device default to "No Audio"
=> fix: default input device selection

src/comfystream/client.py, ui/src/components/control-panel.tsx
PR adds the support for dynamic node update in multi prompt scenario. Thanks to Ashwin 🙏
- The logic remains the same but instead of sending a single prompt in get_available_nodes we now send a dict - {prompt_index: nodes_info} and with every update_prompts call we get a list of all the prompts in order
- Removed the LoadTensor and SaveTensor from the skip list because we soon might be added more params to it like buffering in LoadAudioTensor
=> feat: multi prompt dynamic node update

scripts/README.md, scripts/monitor_pid_resources.py, scripts/requirements.txt
This pull request adds a small profiler script developers can use while working on ComfyStream to check resource usage and potential bottlenecks. It will provide the developer with the following information:
<details>
<summary>Show Data</summary>
```bash
(comfystream) [16:26:29] ricks@rick-dev-station:~/development/livepeer/ai/comfystream_ws/comfystream/scripts$ sudo env "PATH=$PATH" python monitor_pid_resources.py --pid  68618 --output resources_output.csv --duration 120 --spy
Monitoring system resources for PID 68618 for 120 seconds...
Running py-spy for deep profiling...
CPU: 298.50%, RAM: 5512.73MB, GPU: 44.00%, VRAM: 3876.00MB
CPU: 299.50%, RAM: 5512.73MB, GPU: 28.00%, VRAM: 3876.00MB
CPU: 296.50%, RAM: 5512.73MB, GPU: 49.00%, VRAM: 3876.00MB
CPU: 307.50%, RAM: 5512.98MB, GPU: …
```
=> feat: add resource profiler script

pyproject.toml
This pull request ensures that the `prometheus-client` dependency is explicitly specified in both `requirements.txt` and `pyproject.toml` for consistency and proper dependency management.
=> fix: include Prometheus client dependency in project.toml

.devcontainer/post-create.sh, docker/entrypoint.sh, ui/package-lock.json
This resolves an error with the livepeer/comfystream:latest image unable to start due to missing ui folder. The new docker CI excluded the ui folder from copying to the image, resulting in this error. The folder is not needed in the image any longer, so it can be removed
=> fix: remove node package install from launch

configs/nodes.yaml
This change reverts the ComfyUI_TensorRT custom node to use the origin branch now that https://github.com/yondonfu/ComfyUI_TensorRT/pull/2 has been merged.
The eliteprox fork was temporarily used in https://github.com/yondonfu/comfystream/pull/126
=> chore: update ComfyUI-TensorRT node to origin branch

server/app.py, server/pipeline.py
This change resolves https://github.com/yondonfu/comfystream/issues/124 which is caused by concurrent worker processes loading the same models in certain workflows.
This change also handles WebRTC data channel errors during frame processing in `app.py` to resolve https://github.com/yondonfu/comfystream/issues/135. Please note these are separate issues.
`max_workers` had been set to `5` in https://github.com/yondonfu/comfystream/pull/10 to allow for more than a single workflow to be executed simultaneously, however, we must refactor the solution to ensure that prompts are always queued to the same worker process, otherwise this error will occur. (See https://github.com/yondonfu/comfystream/issues/73)
This issue was also occurring intermittently midstream due to the active worker process …
=> fix: prevent `AssertionError` by setting `max_workers` to 1

scripts/monitor_pid_resources.py
This pull request fixes a NoneType error in the resource monitoring script that occurs when certain processes lack a name.
=> fix(dev): handle NoneType error in monitor script

nodes/__init__.py
This pull request ensures that Audio Tensor nodes are correctly registered in the `nodes/__init__.py` file, allowing them to be utilized in ComfyStream.
=> fix(server): ensure Audio Tensor nodes are properly registered

ui/src/components/settings.tsx
This pull request fixes a bug that caused the camera to always revert to the default, preventing users from disabling it. This fix ensures that the default camera is only selected on the first initial load, and users can disable it afterwards. It also applies a quick patch to warn people if no camera or microphone is selected.
@eliteprox, we should probably clean the logic in the future. Now we both use https://zod.dev/, and the [radix required logic](https://www.radix-ui.com/primitives/docs/components/select).
=> fix(ui): allow users to disable the camera after initial load

configs/nodes.yaml, workflows/comfystream/sd15-multi-cnet-depthanything-face-api.json, workflows/comfyui/sd15-multi-cnet-depthanything-face.json
This change introduces an update to the main workflow that uses a new and optimized face mesh estimating node as opposed to the existing community implementation. 
The optimized node was implemented from scratch, and increases FPS by 37.5% in my environment.
The optimized node has been added to the nascent ComfyUI-Stream-Pack repo; it's integration to the main branch of that repo is pending. In the meantime, use the following branch when installing the nodes for testing this workflow:
https://github.com/livepeer/ComfyUI-Stream-Pack/tree/expose_feature_bank_to_comfyui
cc: @rickstaa
=> feat: add optimized face mesh estimator
